name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install htmlhint stylelint stylelint-config-standard eslint --save-dev

      # Step 4: Create a basic stylelint config if not already present
      - name: Create Stylelint configuration
        run: |
          echo '{
            "extends": "stylelint-config-standard",
            "rules": {
              "block-no-empty": true,
              "color-no-invalid-hex": true
            }
          }' > .stylelintrc.json

      # Step 5: Run HTMLHint
      - name: Lint HTML files with HTMLHint
        run: npx htmlhint '**/*.html'

      # Step 6: Run Stylelint
      - name: Lint CSS files with Stylelint
        run: npx stylelint '**/*.css'

      # Step 7: Run ESLint
      - name: Lint JS files with ESLint
        run: npx eslint '**/*.js'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Directory to deploy
