name: CI/CD Workflow

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Fix permissions
      run: chmod +x node_modules/.bin/htmlhint

    - name: Lint HTML
      run: ./node_modules/.bin/htmlhint '**/*.html'

    - name: Verify permissions
      run: ls -l node_modules/.bin/

  deploy:
      if: github.ref == 'refs/heads/main'
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./ 
